---
- name: "Refresh services"
  block:
    - systemd:
        state: restarted
        daemon_reload: no
        name: "{{ item.name }}"
      loop: "{{ systemd_services_to_refresh }}"
  when:
    - systemd_services_to_refresh is defined
    - systemd_services_to_refresh | length > 0

- name: "Systemd Daemon reload"
  systemd:
    daemon_reload: yes
