---
- include_tasks: user_setup.yml

- include_tasks: static_content.yml

- set_fact:
    nginx_config_dir: "{{ nginx.home }}/config"

- assert:
    that:
      - nginx_config_dir is defined
      - nginx_config_dir != ""
    quiet: true
    fail_msg: "Invalid parameters"

- stat:
    path: "{{ nginx_config_dir }}"
  register: nginx_config_dir_path

- assert:
    that:
      - nginx_config_dir_path is defined

- include_tasks: nginx_config.yml

- include_tasks: static_content.yml

- include_tasks: http_cache_setup.yml
  when: nginx.caches is defined

- include_tasks: ssl.yml
  when: nginx.https is defined
