---
- assert:
    that:
      - monit_webapp_username is defined
      - monit_webapp_username != ""
      - monit_webapp_password is defined
      - monit_webapp_password != "" 
    quiet: true

- name: "Deploy secrets to authentificate when proxying requests to Monit"
  template:
     src: nginx.monit.passwd.j2
     dest: "{{ nginx_config_dir }}/monit.passwd"
     owner: nginx
     group: nginx
     mode: 0644
