---
- name: Automate VM with Ansible
  hosts: all
  gather_facts: true
  become: yes

  vars_files:
    - vars/vault.yml
    - vars/cci.yml
    - vars/java.yml

  pre_tasks:
    - name: "Load Secrets from Vault"
      ansible.builtin.include_role:
        name: "vault"

    - name: Check registration status
      ansible.builtin.command: subscription-manager list
      register: registration_status
      ignore_errors: true

    - name: Register if not already registered
      when: registration_status.rc != 0
      community.general.redhat_subscription:
        state: present
        username: "{{ cci_worker_rhel_subscription_username }}"
        password: "{{ cci_worker_rhel_subscription_password }}"
        autosubscribe: yes
        force_register: true

    - name: Update yum
      ansible.builtin.yum:
        name: "*"
        state: latest

    - name: Install pip3
      ansible.builtin.package:
        name: python3-pip

    - name: "Install hvac python library"
      ansible.builtin.pip:
        name: hvac>=1.2.1
        executable: pip3

    - ansible.builtin.include_role:
        name: fast_yum_install
      vars:
        package_name: "{{ pretaskfiles }}"
      with_items:
        - firewalld
        - zip
        - podman
        - podman-docker
        - jq
      loop_control:
        loop_var: pretaskfiles

    - name: "Ensure jaegertracing docker image is downloaded for tests"
      containers.podman.podman_image:
        name: "quay.io/jaegertracing/all-in-one:latest"
      become: yes
      become_user: "{{cci_worker_username}}"

  tasks:
    - ansible.builtin.include_role:
        name: "{{ taskfiles }}"
      with_items:
        - cci_worker
        - sshd
        - sudoers
        - ssh
        - java
        - java_certs
        - old_releases
      loop_control:
        loop_var: taskfiles
