---
- hosts: localhost
  gather_facts: no
  become: yes
  become_user: root
  vars_files:
      - vars/aphrodite.yml
      - vars/olympus.yml
      - vars/monit.yml
      - vars/caches.yml
      - vars/java.yml
      - vars/java_certs.yml
      - vars/jobs.yml
      - vars/component-alignment.yml
      - vars/mailer.yml
  roles:
    # stage 1 - OS settings and optimizations
    - selinux
    - motd
    - bashrc
    - kdump
    - sysctl
    - tuned
    # stage 2 - main services
    - sshd
    - ssh
    - ares
    - jenkins
    - nginx
    - java
    - java_certs
    - old_releases
    - systemd
    - podman
    - payload_status
    - monit
    # stage 3 - auth and sudoers.yml
    - component_alignment
    - pr_processor
    - aphrodite
    - jobs
  pre_tasks:

    - hostname:
        name: "{{ ansible_hostname }}"

    - include_role:
        name: account
      vars:
        account:
          username: "{{ override_jenkins_name }}"
          uid: "{{ override_jenkins_uid }}"
          group: "{{ override_jenkins_group }}"
          gid: "{{ override_jenkins_gid }}"
          home: /home/jenkins

#    - include_role:
#        name: account
#      vars:
#        account:
#          username: "{{ jenkins.username }}"
#          uid: "{{ jenkins.uid }}"
#          group: "{{ jenkins.groupname }}"
#          gid: "{{ jenkins.gid }}"
#          home: "{{ jenkins.home }}"
