---
- hosts: localhost
  gather_facts: no
  become: yes
  become_user: root
  vars_files:
      - vars/olympus.yml
      - vars/monit.yml
      - vars/caches.yml
      - vars/java_certs.yml
      - vars/jobs.yml
      - vars/component-alignment.yml
      - vars/mailer.yml
  roles:
    # stage 1 - OS settings and optimizations
#    - selinux
#    - motd
#    - bashrc
#    - kdump
#    - sysctl
#    - tuned
#    # stage 2 - main services
#    - sshd
    - podman
#    - java_certs
#    - old_releases
    - jenkins
    - nginx
    - monit
    # stage 3 - auth and sudoers.yml
    # TODO
  pre_tasks:
    - hostname:
        name: "{{ ansible_hostname }}"
