---
- hosts: localhost
  gather_facts: no
  become: yes
  become_user: root
  vars_files:
      - vars/olympus.yml
      - vars/monit.yml
      - vars/caches.yml
      - vars/java.yml
      - vars/java_certs.yml
      - vars/jobs.yml
      - vars/component-alignment.yml
      - vars/mailer.yml
  roles:
    # stage 1 - OS settings and optimizations
    - selinux
    - motd
    - bashrc
    - kdump
    - sysctl
    - tuned
#    # stage 2 - main services
    - sshd
    - podman
    - java
    - java_certs
    - old_releases
    - jenkins
    - nginx
    - monit
    # stage 3 - auth and sudoers.yml
    # TODO
  pre_tasks:

    - name: permit traffic in default zone for https service
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
      loop:
        - ssh
        - http
        - https

    - hostname:
        name: "{{ ansible_hostname }}"

    - include_role:
        name: account
      vars:
        account:
          username: "{{ override_jenkins_name }}"
          uid: "{{ override_jenkins_uid }}"
          group: "{{ override_jenkins_group }}"
          gid: "{{ override_jenkins_gid }}"
          home: /home/jenkins
