---
- assert:
    that:
      - jdk_list is defined 
      - jdk_list is iterable

- name: "Provisioning self-signed certificate to JDKs"
  include: tasks/java_certs.yml
  loop: "{{ jdk_list }}"
  loop_control:
    loop_var: jdk

- name: Symlink to Java default version
  file:
    src: "{{ jdk_default  }}"
    dest: "{{ jdk_default_link }}"
    state: link
  when: jdk_default_link is defined
