---
- include_role:
    name: fast_yum_install
  vars:
    package_name: monit

- assert:
    that:
      - monit is defined
      - monit.daemon is defined
      - (monit.daemon | int) > 0
    quiet: true
    fail_msg: "Invalid Monit configuration"

- name: "Deploy Monit main config"
  template:
    src: templates/monitrc.j2
    dest: /etc/monitrc
    mode: 0700
    owner: root
    group: root

- name: "Ensures monit.conf.d is properly created and set"
  file:
    state: directory
    path: /etc/monit.d/
    owner: root
    group: root

- firewalld:
    port: "{{ monit.webapp.port}}/tcp"
    permanent: yes
    state: enabled
  when:
    - monit.webapp is defined
    - monit.webapp.port is defined
    - (monit.webapp.port | int) > 0

- service:
    name: monit
    state: started
    enabled: yes
