---
- name: "Ensure home for synchronizer scripts exists."
  file:
    state: directory
    path: "{{ jobs.synchronizer.home }}" 
    owner: jenkins
    group: jenkins

- name: "Deploy scripts for jobs_sync"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: jenkins
    group: jenkins
    mode: '0755'
  loop:
    - { src: "{{ jobs.synchronizer.script.src }}", dest: "{{ jobs.synchronizer.home }}/{{ jobs.synchronizer.script.name }}" }
    - { src: "{{ jobs.synchronizer.container.src }}", dest: "{{ jobs.synchronizer.home }}/{{ jobs.synchronizer.container.name }}" }
