---
- name: "Generating job configuration for {{ item.id }}"
  template:
    src: templates/job-template.yml.j2
    dest: "{{ jenkins.jobs_home }}/{{ item.id }}.yml"
    owner: jenkins
    group: jenkins
    mode: 0644
  register: job_config_result
  notify:
    - sync_jobs

- name: "Job {{ item.id }} needs to be synchronised"
  block:
    - set_fact:
        add_to_list:
          - "{{ item.id }}"

    - set_fact:
        jenkins_jobs_to_update_list: "{{ jenkins_jobs_to_update_list }} + {{ add_to_list }}"
  when:
    - job_config_result is defined
    - job_config_result.changed
