- name: "Deploy cron-job for Ansible report"
  template: src=templates/cron-ansible.j2 dest=/root/cron-ansible mode=755 owner=root group=root

- name: "Set up cronjob for Ansible report (daily)"
  cron: name="Ansible Daily Report" minute="0" hour="0" job="/root/cron-ansible"

- name: "Deploy cron-job for Monit Status"
  template: src=templates/cron-monit.j2 dest=/root/cron-monit mode=755 owner=root group=root

- name: "Set up cronjob for Monit report (weekly)"
  cron: name="Monit Weekly Report" special_time=weekly job="/root/cron-monit"

- name: "Deploy cron-job for logs cleaning"
  template: src=templates/cron-cleaning-logs.j2 dest=/root/cron-cleaning-logs mode=755 owner=root group=root
  with_items: "{{ logs_cleaning }}"

- name: "Set up cronjob for cleaning logs older than a month (daily)"
  cron: name="Cleaning logfiles" special_time=daily job="/root/cron-cleaning-logs"

- name: "Deploy cron-job for Docker stopped containers cleaned"
  copy: src=files/cron-cleaning-docker-stopped-containers.sh dest=/root/cron-cleaning-docker-stopped-containers mode=755 owner=root group=root

- name: "Delete all stopped docker containers on a weekly basis"
  cron: name="Delete all stopped containers" minute=0 hour=10 weekday=2 job="/root/cron-cleaning-docker-stopped-containers >> /var/log/docker.deleted.containers.log"
