- name: "Ensure JBossSET CI Scripts are installed"
  yum: name=jboss-set-ci-scripts update_cache={{ yum.update_cache }} state=installed

- name: "Add the 'ops' folder to root user PATH"
  copy: src=files/root_bashrc dest=/root/.bashrc owner=root group=root
