- set_fact: package_name={{ jboss.package_name }}
- name: "Ensures jboss-eap7 RPM package is installed"
  import_tasks: tasks/rpminfo.yml  
 
- name: "Created config directory for jboss-eap7"
  file: path=/etc/jboss-eap7/ state=directory group=jboss owner=jboss

- name: "Deploy configuration for jboss-eap7"
  template: src=templates/eap7-standalone.service.j2 dest=/usr/lib/systemd/system/eap7-standalone.service group=jboss owner=jboss

- name: "Deploy init script for jboss-eap7"
  copy: src=files/jboss-eap7 dest=/etc/init.d/jboss-eap7 owner=root group=root mode=755 

- name: "Set up module dir for Postgres JDBC Driver"
  file: path={{ jboss.home }}/modules/org/postgresql/main/ state=directory group=jboss owner=jboss

- name: "Deploy JDBC driver for PQSL"
  copy: src=files/postgresql-8.4-703.jdbc4.jar dest={{ jboss.home }}/modules/org/postgresql/main/ group=jboss owner=jboss

- name: "Deploy module.xml"
  copy: src=files/module.xml dest={{ jboss.home }}/modules/org/postgresql/main/module.xml group=jboss owner=jboss 

- name: "Ensure JBoss EAP 7 is running" 
  service: name='eap7-standalone' state=started enabled=yes
