- set_fact:
    package_name: logrotate
    logrotate_folder: '/etc/logrotate.d/'

- name: Checks that logrotate is installed
  import_tasks: tasks/rpminfo.yml

- name: Checks that EAP logrotate policy is defined
  template:
    src: "templates/{{ item }}"
    dest: "{{ logrotate_folder }}"
    owner: 'root'
    group: 'root'
  with_items:
    - eap-server-logrotate.conf.j2
    - eap-console-logrotate.conf.j2
