- name: "Deploy a {{ ansible_nodename }} specific setings.xml to help jobs use the HTTP Maven Cache"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: jboss
    group: jboss
    mode: '0644'
  with_items: "{{ settings_xml_files }}"

- name: "Check that settings.xml files are valid (XML)"
  shell: xmlwf {{ item.dest }} | wc -l
  register: xmlwf_result
  failed_when: "xmlwf_result.stdout|float > 0"
  changed_when: false
  with_items: "{{ settings_xml_files }}"

- name: "Deploy harmonia-build script"
  template:
    src: templates/harmonia-eap-build.j2
    dest: /usr/local/bin/harmonia-eap-build
    owner: root
    group: root
    mode: 0755

- name: "Link harmonia-eap-build to proper name"
  file: 
    state: link 
    src: /usr/local/bin/harmonia-eap-build
    dest: /usr/local/bin/harmonia-launcher
    owner: root
    group: root
    mode: 0755
   
- block:
  - name: "Link to previous for compat purpose"
    file: 
      state: link 
      src: /usr/local/bin/harmonia-eap-build
      dest: /opt/jboss-set-ci-scripts/harmonia-eap-build
      owner: root
      group: root
  when: "'thunder' in ansible_hostname"
   


