- name: Check if extra local ip are configured
  template: src=ifcfg.j2 dest=/etc/sysconfig/network-scripts/ifcfg-{{ item.name }} mode=644
  with_items: "{{ devices_list }}"

- name: Check files attributes and ownership on /usr/share
  file: state=directory owner=root group=root mode=0755 dest=/usr/share

- name: Check /etc/security/limits.conf is correct
  copy: src=limits.conf dest=/etc/security/limits.conf owner=root group=root mode=0644

- name: Check if group docker exists
  group: name=docker state=present

- name: Check that docker user are in group
  user: name={{ item }} groups=docker append=yes
  with_items:
  - dominik
  - dpospisi
  - belaran
