- set_fact: package_name=postgresql-server
- name: Install PostgreSQL
  import_tasks: tasks/rpminfo.yml  
 
- name: Init PostgesQL Db
  command: creates=/var/lib/pgsql /usr/bin/postgresql-setup initdb
  register: datadir_init
  #become: yes
  #become_user: postgres

- name: Ensure the PostgreSQL service is running 
  service: name=postgresql state=started enabled=yes
  when: datadir_init is success
