- name: "Ensure pull-request-processor folder exists"
  file: name=/home/jboss/pull-request-processor state=directory owner=jboss group=jboss

- name: "Deploy Pull Request Processor configuration"
  template: src=templates/aphrodite.json.j2 dest=/home/jboss/pull-request-processor/aphrodite.json owner=jboss group=jboss mode=640
