---
- assert:
    that:
      - motd.home is defined
      - motd.home != ""
    quiet: true

- stat:
    path: "{{ motd.home }}"
  register: is_motd_home

- assert:
    that:
      - is_motd_home.stat.exists
    quiet: true

- set_fact:
    file_to_remove: "{{ motd.home }}{{ item }}"

- stat:
    path: "{{ file_to_remove }}"
  register: is_file_to_remove

- file:
    path: "{{ file_to_remove }}"
    state: absent
  when: is_file_to_remove.stat.exists
