---
component_upgrade_create_db_url: "https://raw.githubusercontent.com/TomasHofman/component-upgrade-logger/main/src/main/resources/init.sql"
known_hosts.pgsql_component_upgrade.ip: "10.88.0.5"
postgres_instances_services_upgrade_ports_mapping:
  - { src: '5432', dest: "{{ pgsql.instances.component_upgrade.port }}" }
postgres_instances_services_upgrade_vars:
  - { name: 'POSTGRES_PASSWORD', value: "{{ pgsql.instances.component_upgrade.password }}" }
  - { name: 'POSTGRES_USER', value: "{{ pgsql.instances.component_upgrade.username }}" }
