---
- name: "Ensure remote images are downloaded"
  include_tasks: podman_pull.yml 
  loop: "{{ podman.images.remotes }}"

- set_fact:
    podman_build: "{{ ares.home }}/podman-build.sh"

- include_tasks: tasks/podman_build.yml
  loop: "{{ podman.images.locals }}"
