---
- name: "Building images for {{ item.name }} [tag: {{ item.tag }}]."
  command: "runuser -u {{ item.owner }} {{ podman_build }} {{ item.name }} {{ item.tag }}"
  register: res
  changed_when: not item.id in (res.stdout_lines | last)

- debug:
    msg: "Images ID for {{ item.name }}: {{ res.stdout_lines | last }}"
