---
- assert:
    that:
      - item is defined
      - item.name is defined
      - item.tag is defined
      - item.owner is defined
      - podman_build is defined
      - item.id is defined
    quiet: true

- name: "Building images for {{ item.name }} [tag: {{ item.tag }}]."
  command: "runuser -u {{ item.owner }} {{ podman_build }} {{ item.name }} {{ item.tag }}"
  register: res
  changed_when: not item.id in (res.stdout_lines | last)

- debug:
    msg: "Images ID for {{ item.name }}: {{ res.stdout_lines | last }}"
  when:
    - item.name is defined
    - res is defined
    - res.stdout_lines is defined
