---
sql_script_to_run: []
pgsql:
  scripts:
    home: /opt/tools/pgsql
  instances:
    component_upgrade:
      db_name: component-upgrade
      username: component-upgrade
      password: "{{ component_upgrade_psql_password }}"
      port: 15432
      create_db:
        name: 'component-upgrade-init.sql'
        url: "{{ component_upgrade_create_db_url }}"
postgres_instances:
  services:
    - name: pgsql-component-upgrade-dev
      image: 'docker.io/library/postgres'
      ip: "{{ known_hosts.pgsql_component_upgrade.ip }}"
      db_name: "{{ pgsql.instances.component_upgrade.db_name }}"
      ports_mapping: "{{ postgres_instances_services_upgrade_ports_mapping }}"
      vars: "{{ postgres_instances_services_upgrade_vars }}"
      readonly_volumes:
        - src: "{{ pgsql.scripts.home }}/{{ pgsql.instances.component_upgrade.create_db.name }}"
          dest: "/docker-entrypoint-initdb.d/{{ pgsql.instances.component_upgrade.create_db.name }}"
