---
- job:
    name: {{ item.id }}
    project-type: pipeline
    parameters:
      - string:
          name: GIT_REPOSITORY_URL
          default: git@github.com:jboss-set/bug-clerk-report-job.git
      - string:
          name: GIT_REPOSITORY_BRANCH
          default: {{ item.git_branch }}
      - string:
          name: JAVA_HOME
          default: {{ item.java_home }}
      - string:
          name: MAVEN_HOME
          default: {{ item.maven_home }}
      - string:
          name: MAVEN_SETTINGS_XML
          default: {{ item.maven_settings }}
    sandbox: true
    pipeline-scm:
      scm:
        - git:
            url: {{ jenkinsfile.git_repo }}
            branches:
              - origin/master
            clean: true
      script-path: bugclerk-pipeline
      lightweight-checkout: true

