---
- assert:
    that:
      - item is defined
      - item.name is defined
      - item.tag is defined
      - item.owner is defined
      - podman_build is defined
    quiet: true

- include_tasks: "podman/inspect.yml"

- name: "Building image for {{ item.name }} [tag: {{ item.tag }}]."
  command: "runuser -l {{ item.owner }} {{ podman_build }} {{ item.name }} {{ item.tag }}"
  register: res
  changed_when:
    - res is defined
    - res.stdout_lines is defined
    - not image_id in (res.stdout_lines | last)
  notify: "Restart podman based services"

- debug:
    msg: "{{ res }}"
  when: 
    - res is defined
    - podman_debug is defined
    - podman_debug is true

- block:
    - set_fact:
        item_image:
          - { name: "{{ item.tag }}", id: "{{ image_id }}" }
  
    - set_fact:
        podman_images: "{{ podman_images }} + {{ item_image }}"
  when:
    - res is defined
    - res.stdout_lines is defined
    - not image_id in (res.stdout_lines | last)
