---
- name: "Ensure remote image {{ item.name }} is downloaded"
  command: "podman pull {{ item.name }}"
  register: podman_pull_result
  changed_when:
    - podman_pull_request is defined
    - podman_pull_request.stdout is defined
    - podman_pull_result.stdout != item.id
  when:
    - podman_pull_enabled is defined

- block:
  - debug:
      msg: "Image for {{ item.name }} was updated : {{ podman_pull_result.stdout }} (previous id was: {{ item.id }}"
    when:
      - podman_pull_result.stdout != item.id

  - set_fact:
      pulled_image:
        - { name: "{{ item.name }}", id: "{{ podman_pull_result.stdout }}" }

  - set_fact:
      podman_images: "{{ podman_images }} + {{ pulled_image }}"

  when:
    - podman_pull_request is defined
    - podman_pull_request.stdout is defined
