---
- ansible.builtin.include_tasks: generate_keys.yml
  loop:
    - "/home/jenkins"
  loop_control:
    loop_var: homedir

- name: "Download CA certs"
  ansible.builtin.get_url:
    url: "{{ cert.url }}"
    dest: "{{ ares.home }}/hephaestus/{{ cert.url | basename }}"
  check_mode: no
  with_items: "{{ root_ca_certs }}"
  loop_control:
    loop_var: cert
  when:
    - root_ca_certs is defined

- name: "Import CA certs"
  community.general.java_cert:
    cert_path: "{{ ares.home }}/hephaestus/{{ cert.url | basename }}"
    keystore_path: "{{ ares.home }}/hephaestus/cacerts"
    cert_alias: "{{ cert.alias }}"
    executable: "{{ jenkins.default_jdk_home }}/bin/keytool"
    keystore_pass: changeit
    keystore_create: yes
    state: present
  with_items: "{{ root_ca_certs }}"
  loop_control:
    loop_var: cert
  when:
    - root_ca_certs is defined
