---
- name: "Build payload_status"
  include_tasks: tasks/deploy_website.yml
  vars:
    item:
      name: 'yarn-buider'
      src: "{{ payload_status.home }}"
      dest: /workspace
      script: '/build.sh'
