---
- block:
  - name: Add Ansible inventory mappings to /etc/hosts
    become: true
    blockinfile:
      path: /etc/hosts
      block: |
        {% for host in hosts.list %}
        {{ host.ip }} {{ host.names }}
        {% endfor %}
  when:
    - hosts is defined
    - hosts.list is defined
    - hosts.list is iterable
    - hosts.list | length > 0
