---
podman:
  home: /opt/podman
  packages:
    - slirp4netns 
    - podman
    - podman-docker
  kernel:
    max_user_namespaces: 28633
    user_namespaces_config_file: /etc/sysctl.d/userns.conf
  images:
    remotes:
      - { name: 'docker.io/library/nginx', id: "{{ podman_image_id_nginx }}" }
    locals:
      - { name: 'automatons', owner: 'jenkins', tag: 'automatons', id: "{{ podman_image_id_automatons  }}" }
      - { name: 'hephaestus', owner: 'root', tag: 'hephaestus', id: "{{ podman_image_id_hephaestus  }}" }
      - { name: 'jenkins-job-builder', owner: 'jenkins', tag: 'jbb', id: "{{ podman_image_id_jbb  }}" }
  services:
    - name: nginx
      image: 'docker.io/library/nginx'
      ip: "{{ known_hosts.nginx.ip | default('10.88.0.2') }}"
      readonly_volumes:
        - { src: '/home/nginx/static', dest: '/usr/share/nginx/html' }
        - { src: '/home/nginx/config/nginx.conf', dest: '/etc/nginx/nginx.conf' }
        - { src: '/home/nginx/config/commons.d/', dest: '/etc/nginx/commons.d/' }
        - { src: '/home/nginx/ssl/', dest: '/etc/nginx/ssl/' }
      readwrite_volumes:
        - { src: '/home/jboss/maven_caches/', dest: '/home/jboss/maven_caches/' }
      add_hosts:
        - { src: "{{ known_hosts.server.name  }}", ip: "{{ known_hosts.server.ip }}" }
        - { src: "{{ known_hosts.podman.name }}", ip: "{{ known_hosts.podman.ip }}" }
      ports_mapping:
       - { src: '80', dest: '80' }
       - { src: '443', dest: '443' }
    - name: hephaestus
      ip: "{{ known_hosts.jenkins.ip | default('10.88.0.3') }}"
      readwrite_volumes:
        - { src: '/home/jenkins', dest: '/var/jenkins_home' }
      add_hosts:
        - { src: "{{ known_hosts.podman.name }}", ip: "{{ known_hosts.podman.ip }}" }
        - { src: "{{ known_hosts.server.name }}", ip: "{{ known_hosts.server.ip }}" }
      ports_mapping:
       - { src: "{{ override_jenkins_port | default('8080') }}", dest: "{{ override_jenkins_port | default('8080') }}" }
