---
name: CI

on:
  pull_request:
  push:
    branches:
      - driver_fix

jobs:
  test:
    name: molecule
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.11']

    steps:
      - name: Checkout the codebase.
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install testing dependencies.
        run: |
          python -m pip install --upgrade pip
          pip install yamllint 'molecule>=25.1.0' 'molecule-plugins[docker]>=23.6.0' python-requests ansible-core flake8 ansible-lint voluptuous
          ansible-galaxy collection install -r requirements.yml

      - name: Run linter
        run: |
          ansible-lint --version
          ansible-lint -v

      - name: "Run molecule tests"
        run: molecule test --all
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: rhel-9
        working-directory: '.'
